#!/usr/bin/env sh

_emacs() {
    emacs "$@"
}

_vim() {
    st -e nvim "$@"
}

case "$1" in
    m) _vim   "$HOME/pkg/dmenu/config.h" ;;
    M) _vim   "$HOME/pkg/dmenukey/config.h" ;;
    D) _vim   "$HOME/.config/dunst/dunstrc" ;;
    d) _emacs "$HOME/pkg/dwm/config.h" "$HOME/pkg/dwm/dwm.c" ;;
    b) _vim   "$HOME/pkg/dwmblocks/config.h" ;;
    e) _emacs "$HOME/.emacs.d/init.el" ;;
    f) _emacs "$HOME/pkg/flybinds/config.h" "$HOME/pkg/flybinds/items.h" "$HOME/pkg/flybinds/flybinds.c";;
    v) _vim   "$HOME/.config/nvim/init.vim" ;;
    l) _vim   "$HOME/pkg/slock/config.h" ;;
    t) _vim   "$HOME/pkg/st/config.h" ;;
    s) _vim   "$HOME/.config/sxiv/exec/key-handler" "$HOME/.config/sxiv/exec/image-info" ;;
    z) _vim   "$HOME/.config/zathura/zathurarc" ;;
esac
